services:
  app:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    environment:
      ADMIN_KEY: ${ADMIN_KEY}
      PATH_TO_DB: ${PATH_TO_DB}
      LOG_LEVEL: ${LOG_LEVEL}
    entrypoint: ["gunicorn", "-b", "0.0.0.0:8080", "blog_app:app"]
    